# -*- coding: utf-8 -*-
"""One place that knows WHERE the system under test is.

Every value is read from the environment with a default that matches the repo's own
documented local layout (frontend/vite.config.js -> :5178 dev / :5179 preview,
.env.example -> KSSL_API_PORT=8600, KSSL_DB_PORT=5460, backend/app.py DEFAULT_DSN).

Nothing here invents a URL, a credential or a table. On staging/prod the front door is
traefik with the `kssl-auth` basicauth middleware (docker-compose.vps.yml labels), user
`kssl`, password generated by deploy/provision_env.sh -- so the suite takes it from the
environment and never guesses it.
"""
import os

# --- addresses -------------------------------------------------------------------------
# The FRONT DOOR: what a browser opens. Locally the vite dev server; on staging/prod
# https://$KSSL_DOMAIN (traefik router kssl-web).
BASE_URL = os.environ.get("KSSL_TEST_BASE_URL", "http://127.0.0.1:5178").rstrip("/")

# The API. Behind the front door it is BASE_URL + /api (traefik router kssl-api,
# PathPrefix(`/api`) -> backend:8600). Directly it is the FastAPI container's port.
# NOTE: /healthz is NOT under /api, so through the front door it is unreachable by design.
API_URL = os.environ.get("KSSL_TEST_API_URL", "http://127.0.0.1:8600").rstrip("/")

# --- authentication --------------------------------------------------------------------
# The ONLY authentication in this system: HTTP Basic, enforced by traefik in front of
# BOTH the UI and /api. There is no login form, no session, no JWT and no roles anywhere
# in backend/app.py or frontend/src -- see TEST_CASES.md, module AUTH.
BASIC_USER = os.environ.get("KSSL_TEST_BASIC_USER", "")
BASIC_PW = os.environ.get("KSSL_TEST_BASIC_PW", "")
AUTH = (BASIC_USER, BASIC_PW) if BASIC_USER else None

# --- database --------------------------------------------------------------------------
DSN = os.environ.get(
    "KSSL_TEST_DSN",
    "host=127.0.0.1 port=5460 dbname=kssl user=postgres password=kssl")

# backend/app.py: SCHEMA = serving_live unless KSSL_SERVE_ORIGIN=all.
SERVE_ORIGIN_ALL = os.environ.get("KSSL_SERVE_ORIGIN") == "all"
SERVED_SCHEMA = "serving" if SERVE_ORIGIN_ALL else "serving_live"

# --- opt-ins ---------------------------------------------------------------------------
# POST /api/bench/submit INSERTs into metrics.adhoc_job. It is the only write path the
# HTTP surface has, so it is off unless the operator turns it on for this run.
ALLOW_WRITES = os.environ.get("KSSL_TEST_ALLOW_WRITES") == "1"

# Performance budgets. Deliberately generous: the dashboard's bootstrap read is the whole
# corpus in one round trip (frontend/src/api/datasetService.js), and client.js gives it
# 30s before it aborts. A budget tighter than the app's own timeout would fail the test
# on something the app considers healthy.
BUDGET_DATASET_S = float(os.environ.get("KSSL_TEST_BUDGET_DATASET_S", "30"))
BUDGET_OPS_S = float(os.environ.get("KSSL_TEST_BUDGET_OPS_S", "10"))
BUDGET_FIRST_PAINT_S = float(os.environ.get("KSSL_TEST_BUDGET_PAINT_S", "45"))

TIMEOUT_S = float(os.environ.get("KSSL_TEST_HTTP_TIMEOUT_S", "60"))


def api(path):
    """Absolute URL for an API path written as it appears in backend/app.py."""
    return API_URL + path


def front(path=""):
    return BASE_URL + path
