#!/usr/bin/env bash
# Provision a fresh STAGING or DEV host. Run ON the target machine, from /opt/kssl/app.
#
#   ./deploy/provision_env.sh staging     # VPS-A
#   ./deploy/provision_env.sh dev         # data centre
#
# Idempotent: an existing .env is never overwritten, and `up -d` on an already-running
# database is a no-op. Safe to re-run after a failed attempt.
#
# It will NOT run against prod. Production is provisioned already and is the one machine
# this whole split exists to leave alone.
set -euo pipefail

ENVN="${1:?usage: provision_env.sh <staging|dev>}"
APP="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$APP"
ENV_FILE="deploy/envs/$ENVN.env"
[ -f "$ENV_FILE" ] || { echo "!! no such environment: $ENVN"; exit 2; }
# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a
[ "${KSSL_DATA_ROLE:-}" = "replica" ] || { echo "!! $ENVN is not a replica environment, refusing"; exit 3; }

echo ">> provisioning $ENVN  prefix=$KSSL_PREFIX  db port=$KSSL_DB_PORT"

# Stamp the machine. deploy.sh reads this and refuses any deploy that names a different
# environment -- the guard against a staging or dev GitHub Environment falling back to the
# repository secrets and landing on production.
#
# REFUSE TO RE-STAMP. This used to overwrite whatever was there, which folds the guard
# under the exact case it exists for: `provision_env.sh staging` run on VPS-B stamps it
# `staging`, production deploys are then refused, and a staging deploy that fell back to
# the repository secrets is ACCEPTED onto production. Changing a machine's identity is a
# deliberate act and needs KSSL_RESTAMP=1.
MARKER="$APP/.KSSL_ENV"
if [ -f "$MARKER" ] && [ "$(tr -d '[:space:]' < "$MARKER")" != "$ENVN" ]; then
  if [ "${KSSL_RESTAMP:-}" = "1" ]; then
    echo "   !! re-stamping $(cat "$MARKER") -> $ENVN (KSSL_RESTAMP=1)"
  else
    echo "!! this machine is already provisioned as '$(tr -d '[:space:]' < "$MARKER")'."
    echo "   Refusing to re-stamp it as '$ENVN'. If that is really what you want:"
    echo "     KSSL_RESTAMP=1 $0 $ENVN"
    exit 6
  fi
fi
echo "$ENVN" > "$MARKER"

# 1. The environment file. Generated here, never copied from production -- a staging or dev
#    leak must not open prod. Compose interpolates the WHOLE file even when only one service
#    is being started, which is why the traefik and llm variables below have to be present
#    even though neither is published in these environments.
if [ -f .env ]; then
  echo "   .env exists, leaving it alone"
else
  umask 077
  cat > .env <<EOF
# $ENVN — generated by provision_env.sh. Own credentials, not production's.
KSSL_ENV=$KSSL_ENV
KSSL_PREFIX=$KSSL_PREFIX
KSSL_DB_PORT=$KSSL_DB_PORT
KSSL_OLLAMA_PORT=$KSSL_OLLAMA_PORT
LLMAPI_PORT=$LLMAPI_PORT
KSSL_DB_NAME=kssl
KSSL_DB_USER=postgres
KSSL_DB_PASSWORD=$(head -c 18 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')
KSSL_DB_CPUS=2
KSSL_DB_MEM=4g
KSSL_API_CPUS=2
KSSL_API_MEM=2g
KSSL_WEB_CPUS=1
KSSL_WEB_MEM=1g
KSSL_LLM_CPUS=2
KSSL_LLM_MEM=4g
KSSL_LLM_THREADS=4
# Placeholders: neither environment is published to the internet -- both are reached over
# SSH or from the box itself -- but compose refuses to interpolate a missing variable.
KSSL_DOMAIN=$ENVN.local
KSSL_ACME_EMAIL=admin@i3softlab.com
KSSL_SERVE_ORIGIN=http://127.0.0.1:$((LLMAPI_PORT - 10))
KSSL_API_PORT=$((LLMAPI_PORT - 10))
KSSL_OLLAMA=http://127.0.0.1:$KSSL_OLLAMA_PORT
KSSL_MODEL=qwen2.5:7b
KSSL_VPS_MODEL=qwen2.5:7b
KSSL_MODELS_DIR=/opt/kssl/models
KSSL_BASIC_AUTH=$ENVN:\$apr1\$placeholder
TAG=latest
EOF
  echo "   wrote .env with a freshly generated database password"
fi

# 1b. The EXTRACTION environment file. Separate from the app's .env because the fleet is
#     its own compose project, and `env_file: .env` in extraction/docker-compose.yml is
#     read at PARSE time -- without this file every `docker compose` call under
#     extraction/ fails, which takes down two things that are supposed to work on a
#     replica host: deploy.sh's extraction recreate, and the `migrate` role that
#     sync_from_prod.sh runs after a swap to bring a restored schema up to date.
#
#     No farm credentials here. The workers are not started on a replica (see below);
#     what this file has to support is `docker compose run --rm migrate`, which needs a
#     DSN and nothing else. Someone bringing the fleet up on this host fills in the LLM
#     block from extraction/.env.example first.
if [ -f extraction/.env ]; then
  echo "   extraction/.env exists, leaving it alone"
else
  umask 077
  # `|| true` because grep exits 1 on no match and this script runs under `set -e`: a
  # pre-existing .env written by hand may spell the line differently, and dying here with
  # no message is worse than the empty-password check two lines down.
  DB_PW="$(grep -m1 '^[[:space:]]*\(export[[:space:]]\+\)\?KSSL_DB_PASSWORD=' .env | cut -d= -f2- | tr -d '"'\''' || true)"
  if [ -z "$DB_PW" ]; then
    echo "!! could not read KSSL_DB_PASSWORD out of $APP/.env -- extraction/.env would carry"
    echo "   an empty password and every migrate would fail to authenticate."
    exit 7
  fi
  cat > extraction/.env <<EOF
# $ENVN extraction — generated by provision_env.sh. Enough to run \`migrate\`; the LLM
# routing below is a placeholder, fill it from .env.example before starting any worker.
KSSL_CORPUS_DSN=host=127.0.0.1 port=$KSSL_DB_PORT dbname=kssl user=postgres password=$DB_PW
KSSL_CORPUS_SRC_DSN=host=127.0.0.1 port=15432 dbname=mallory user=mallory password=CHANGEME
OLLAMA_URL=http://127.0.0.1:$LLMAPI_PORT
OLLAMA_API_KEY=
# REQUIRED FOR THE FILE TO PARSE AT ALL. extraction/docker-compose.yml has
# \${PUNE_API_KEY:?...} on worker-pune, and compose interpolates the WHOLE file at parse
# time no matter which service is being run -- so without this line \`compose run --rm
# migrate\` and \`compose build\` both fail, which is every use this file has on a replica.
# \`:?\` rejects EMPTY as well as unset, so it needs a value, not a blank.
PUNE_API_KEY=unset-on-replica-no-pune-workers-here
C_OPENAI=1
C_MODEL=text-model
C_GUIDED=0
C_GLINER_URL=http://127.0.0.1:$LLMAPI_PORT/v1/gliner
KSSL_HEALTH_URL=http://127.0.0.1:$LLMAPI_PORT/v1/nodes
KSSL_MIN_HEALTHY_NODES=1
KSSL_NODE=farm
C_LIVE_NODES=farm,vps-a
C_NODE_MAX_CLASS=7
FEED_EVERY_S=600
KSSL_SYNC_LIMIT=500
KSSL_SINCE_DAYS=3
KSSL_MIN_TEXT=600
KSSL_MAX_TEXT=9000
KSSL_WORKLIST_LIMIT=2000
KSSL_MAX_LANE=7
LAYERB_EVERY_S=3600
C_CTX_MAX=8192
C_DOC_DEADLINE=3600
EOF
  echo "   wrote extraction/.env (migrate-capable; LLM routing is a placeholder)"
fi

# 2. Port check before starting anything. Both replica hosts already carry other people's
#    containers -- VPS-A runs the crawler and comprehension dashboards, the data centre runs
#    the crawler itself -- and a port clash surfaces as a confusing compose error much later.
for p in "$KSSL_DB_PORT" "$KSSL_OLLAMA_PORT" "$LLMAPI_PORT"; do
  if ss -ltn 2>/dev/null | grep -q ":$p "; then
    echo "!! port $p is already in use on this host -- edit $ENV_FILE before continuing"; exit 4
  fi
done
echo "   ports $KSSL_DB_PORT/$KSSL_OLLAMA_PORT/$LLMAPI_PORT are free"

# 3. The database only. frontend/backend come from the deploy, which needs an image tag;
#    extraction stays down until someone asks for it, because these fleets share the farms
#    with production's.
docker compose -f docker-compose.vps.yml -f "$COMPOSE_OVERLAY" up -d db
echo "   waiting for $KSSL_PREFIX-db to accept connections"
for _ in $(seq 1 30); do
  if docker exec "$KSSL_PREFIX-db" pg_isready -U postgres >/dev/null 2>&1; then break; fi
  sleep 2
done
docker exec "$KSSL_PREFIX-db" pg_isready -U postgres

# 4. PROVE THE EXTRACTION COMPOSE FILE PARSES, here, where it is cheap to fix. Compose
#    interpolates the entire file at parse time -- every ${VAR:?} in it, not just the
#    service being run -- so one missing variable breaks `compose run --rm migrate` and
#    `compose build` alike. Both matter on a replica: the first is the last step of every
#    sync_from_prod.sh, the second is part of every deploy. Without this check the failure
#    surfaces later and in a worse place: after a database swap, with the replica left on
#    production's schema.
echo "   checking the extraction compose file parses with this environment"
if ! ( cd extraction && docker compose -f docker-compose.yml -f "docker-compose.$ENVN.yml" config -q ); then
  echo "!! extraction/docker-compose.yml does not parse with extraction/.env as written."
  echo "   Every variable the file marks required (\${VAR:?...}) must have a NON-EMPTY value."
  echo "   Compare against extraction/.env.example and re-run."
  exit 8
fi
echo "   extraction compose parses"

cat <<EOF

>> $ENVN is provisioned. Next:

   1. load production's data:
        DUMP_FILE=/tmp/prod.dump ./deploy/sync_from_prod.sh $ENVN
      (stream the dump from a machine that can reach both. The schema list is not
       optional: sync_from_prod.sh REFUSES a dump with no serving_live, because that is
       the schema backend/app.py actually queries.
         ssh <prod> "docker exec -i kssl-db pg_dump -U postgres -d kssl -Fc --no-owner --no-acl \\
             -n public -n extracted -n serving -n serving_live -n metrics \\
             -T public.prio -T public.prio_demote_backup -T public.oversize_backup" \\
           | ssh <this host> 'cat > /tmp/prod.dump')

   2. push to the '$ENVN' branch -- CI builds the images and deploys frontend+backend here.

   Extraction is intentionally NOT started -- these fleets share the farms with
   production's. Bring it up only when you want it, and fill in the LLM block of
   extraction/.env first or every worker will sit in the health gate:
        cd extraction && docker compose -f docker-compose.yml -f docker-compose.$ENVN.yml up -d
EOF
